version: "3"
services:
  mcr_backend:
    image: dishang09/mcr_backend
    container_name: mcr_backend
    working_dir: /mycleanroom/backend
    stdin_open: true
    ports:
      - 13131:12345
    volumes:
      - appvol:/mycleanroom/backend/logs
    networks:
      mcr_net:
        ipv4_address: 172.30.1.9
    entrypoint: ["npm", "start"]
    environment:
      PORT: 12345
      DB_URI: "mongodb+srv://dishang09:5kAI2GcRAQYpWSX8@mcrcluster.ygwhkup.mongodb.net/?retryWrites=true&w=majority"

  mcr_frontend:
    image: dishang09/mcr_frontend
    container_name: mcr_frontend
    expose:
      - 9090
    ports:
      - "9090:80"
    depends_on:
      - mcr_backend
    stdin_open: true
    networks:
      mcr_net:
        ipv4_address: 172.30.1.11

volumes:
  appvol:

networks:
  mcr_net:
    ipam:
      driver: default
      config:
        - subnet: 172.30.1.0/24
