module.exports = {
  API_NOT_FOUND: "API NOT FOUND",
  INTERNAL_SERVER_ERROR: "INTERNAL SERVER ERROR",
  DATA_VALIDATION_ERROR: "INVALID DATA",
  INVALID_VALIDATOR: "UNDEFINED VALIDATOR",
  BAD_REQUEST: "BAD REQUEST",
  UNAUTHORIZED: "INVALID USERNAME OR PASSWORD",
};
